version = 0.1

[default.deploy.parameters]
stack_name = "vcm-preprocessing-stack"
resolve_s3 = true
s3_prefix = "vcm-preprocessing-stack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["VcmPreprocessFunction=099220985688.dkr.ecr.eu-central-1.amazonaws.com/vcmpreprocessingstackd2d447f8/vcmpreprocessfunction840bb5d8repo"]
parameter_overrides = "InvoiceBucketName=\"vcm-invoices-upload-kevin-01\" AlertEmailFrom=\"kevindellapiazza1@gmail.com\" AlertEmailTo=\"kevindellapiazza1@gmail.com\" SlackWebhookUrl=\"https://hooks.slack.com/services/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\""
