AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: VCM Invoice Validation Pipeline

Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    MemorySize: 256

Resources:
  VcmTextractLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vcm-textract-lambda
      CodeUri: ../src/vcm-textract-lambda/
      Handler: lambda_function.lambda_handler
      Events:
        InvoiceUploaded:
          Type: S3
          Properties:
            Bucket: vcm-invoice-uploads-kevin           
            Events: s3:ObjectCreated:*

  VcmAlertLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vcm-alert-lambda
      CodeUri: ../src/vcm-alert-lambda/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          SENDER_EMAIL: kevindellapiazza1@gmail.com        
          RECIPIENT_EMAIL: kevindellapiazza1@gmail.com     
      Events:
        ValidationFailed:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - invoice.validation
              detail-type:
                - ValidationFailed
